version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Mexico_City
  open-pull-requests-limit: 10
  reviewers:
  - AdrianDeAnda
  allow:
  - dependency-type: direct
  - dependency-type: indirect
